project:
  type: website
  output-dir: docs

website:
  title: "Movement Visualizations"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: lux
    toc: true

editor: visual

